print("My Name is Pujana Banstola")
print("I am a student")
print("I am from Pokhara")
print("I like to learn new things")
print("I like to explore ")
print("I am learning python")
print("I am learning python from technology channel")
print("I am planning to start my career in tech by learning python through technology channel")
print("My class starts from 8 to 9 in evening ")
print("I am fully plannng to give continuity to this course and my career")